---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
spec:
  serviceName: mongodb-service
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongoadmin
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb-password
              name: restful-secrets
        image: mongo
        name: mongodb
        ports:
          - containerPort: 27017
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
        volumeMounts:
          - mountPath: /data/db
            name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"] # just one node can read/write at a time to this volume
        resources:
          requests:
            storage: 1Gi


---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  clusterIP: None # headless service
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
